### PR TITLE
Update grads.py

### PR DESCRIPTION
**Pull request by RikHendriks**
Added the derivatives of the following functions:
np.tan()
np.arccos()
np.arcsin()
np.arctan()

Added tests for the following functions:
np.cos()
np.sin()
np.tan()
np.cosh()
np.sinh()
np.tanh()
np.arccos()
np.arcsin()
np.arctan()

Changed the position of the (cos, sin, tan) functions, such that they are correctly ordered.

### CODE REVIEW

**Comment by RikHendriks** [comment]
I see that the test failes on:
module 'astor' has no attribute 'codegen'

This is probably because Astor released a new update two hours ago:
https://github.com/berkerpeksag/astor/releases

**Comment by mdanatg** [comment]
I believe so, opened #41

**Comment by mdanatg** [comment]
There is another slight wrinkle: when adding simple functions to functions.py, they will be by default picked up by both reverse and forward tests. This PR defines adjoints, which are useful for reverse mode (gradients), but the forward tests will fail because it can't find tangents which are useful for forward mode (derivatives). Those are defined in tangents.py.

I will pull this change, but we'll need to define the corresponding missing tangents as well. Are you interested in doing it? If not, I can add them.

**Comment by RikHendriks** [comment]
I am interested in doing that, but I don't have time at the moment. So I will be doing that tomorrow.

**Pull request merged**
