### PR TITLE
Remove explicit dependence on TensorFlow

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes https://github.com/google/tangent/issues/63

### CODE REVIEW

**Comment by mrocklin** [comment]
Passing the CLA information onto my company's legal department (I work for Anaconda Inc.)

**Comment by alexbw** [comment]
Hey @mrocklin, thanks for the PR! Once the CLA stuff clears I'll take a closer look, but an initial skim looks good to me.

**Comment by mrocklin** [comment]
It looks like my current employer, Anaconda Inc, may already have signed a corporate CLA

**Comment by mrocklin** [comment]
> Do you need extra attention here then? 

I don't think so.  This work falls under my employment.  Assuming that my information is correct and Anaconda Inc has already submitted a corporate CLA then I believe that this project should be covered from an intellectual property standpoint.

> Or are we good to go

I believe so

**Comment by alexbw** [comment]
Ok cool. I can't merge until the merge-bot is happy, so go ahead and follow whatever steps it needs, and that'll unblock the merge. We should only have to do this once, and any future contributions should go smoothly.

**Comment by bartvm** [comment]
Continuum Analytics is on file as having a corporate CLA, but for the bot to recognize that I think these steps must be followed (Anaconda has to add you to a specific Google group, you have to use your corporate e-mail to author Git commits, and your corporate e-mail must be added to your GitHub account): https://cla.developers.google.com/about#add-contributors

**Comment by mrocklin** [comment]
Rather than deal with the constraints listed above I've gotten permission from my employer to separately sign the individual contributor agreement.

**Pull request merged**
