### PR TITLE
Try flake8 testing for Python syntax errors or undefined names

### PR DESCRIPTION
**Pull request by cclauss**
[336 undefined names](https://travis-ci.org/google/tangent/builds/299641834?utm_source=github_status&utm_medium=notification) in both Python 2 and Python 3.

### CODE REVIEW

**Comment by bartvm** [comment]
These aren't actually errors. Tangent generates Python code, for which it uses "code quotes" (templates). These templates are never actually run; they are parsed into an abstract syntax tree (AST) which is then transformed before being turned back into source code. During that processing, the expression `d[x]` is replaced with the gradient of `x` (as you can see, all the errors are about `d` not being defined).

**Comment by mdanatg** [comment]
It might be useful to add 'd' and 'tangent' to --builtins; they account for the vast majority of hits. One of those I think was an actual error, and the rest were similar constructs in tests (those would probably be fine with individual overrides). Once those are fixed, I think we could run flake8.

**Comment by cclauss** [comment]
@bartvm Your call...  Do you want to reopen so that I can try @mdanatg suggestion or leave closed?

**Comment by bartvm** [comment]
Yes, sure!

**Comment by bartvm** [comment]
It's choking on some of the tests, which define functions that are never supposed to be run. Could you add `--exclude tests`?

**Pull request merged**
